### ISSUE TITLE
多线程并发操作是安全的吗？

### ISSUE THREAD

**Issue by QuietMinder** [exilon/QuickDAO#1]
你好 请问多线程并发操作数据库是安全的吗？

**Comment by exilon** [comment]
是的，原则上，它已在多个多进程程序中使用，没有问题。

**Comment by QuietMinder** [comment]
Ok thanks for bringing such a great library i have been using some things including the basic library, thanks!

**Comment by exilon** [comment]
Thanks for your comments.
