### ISSUE TITLE
 Quick.DAO.Query.pas - Undeclared identifier: 'Serialize'

### ISSUE THREAD

**Issue by eduardomrj** [exilon/QuickDAO#3]
[dcc32 Error] Quick.DAO.Query.pas(200): E2003 Undeclared identifier: 'Serialize'

method is not being found in this class, please have a solution?

**Comment by exilon** [comment]
You need QuickLib [https://github.com/exilon/quicklib](https://github.com/exilon/quicklib) to compile Quick.DAO
